# Generated by Django 5.2.6 on 2025-10-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('customer_email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('customer_venmo', models.CharField(blank=True, max_length=100, verbose_name='Venmo Username')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('has_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('available_sizes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.collection')),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='order.productcategory')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='order.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_color', models.CharField(blank=True, max_length=50, null=True)),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Youth XS'), ('YS', 'Youth Small'), ('YM', 'Youth Medium'), ('YL', 'Youth Large'), ('YXL', 'Youth XL'), ('AS', 'Adult Small'), ('AM', 'Adult Medium'), ('AL', 'Adult Large'), ('AXL', 'Adult XL'), ('2X', 'Adult 2X'), ('3X', 'Adult 3X'), ('4X', 'Adult 4X')])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.productcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='order.product')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
    ]
