# Generated by Django 5.2.6 on 2025-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
