# Generated by Django 5.2.6 on 2025-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_productvariant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
