# Generated by Django 5.2.6 on 2025-09-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_product_size_orderitem_size_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
