# Generated by Django 5.2.6 on 2025-11-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Youth XS'), ('YS', 'Youth Small'), ('YM', 'Youth Medium'), ('YL', 'Youth Large'), ('YXL', 'Youth XL'), ('AS', 'Adult Small'), ('AM', 'Adult Medium'), ('AL', 'Adult Large'), ('AXL', 'Adult XL'), ('2X', 'Adult 2X'), ('3X', 'Adult 3X'), ('4X', 'Adult 4X'), ('5X', 'Adult 5X'), ('OS', 'One-Size')]),
        ),
    ]
