# Generated by Django 5.2.6 on 2025-09-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='organization',
            new_name='collection',
        ),
    ]
