# Generated by Django 5.2.6 on 2025-09-24 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_organization_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collection',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='collection_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.collection'),
        ),
    ]
