# Generated by Django 5.2.6 on 2025-09-24 01:43

from django.db import migrations, models


def migrate_sizes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    
    Product = apps.get_model("order", "Product")
    products = Product.objects.using(db_alias).prefetch_related("available_sizes")
    for product in products:
        product.available_sizes_temp = [
            size.code for size in product.available_sizes.all()
        ]
        product.save()
    
    OrderItem = apps.get_model("order", "OrderItem")
    order_items = OrderItem.objects.using(db_alias).select_related("size")
    for order_item in order_items:
        order_item.size_temp = order_item.size.code
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_collection_orderitem_collection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes_temp',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_temp',
            field=models.CharField(choices=[('XS', 'Youth XS'), ('YS', 'Youth Small'), ('YM', 'Youth Medium'), ('YL', 'Youth Large'), ('YXL', 'Youth XL'), ('AS', 'Adult Small'), ('AM', 'Adult Medium'), ('AL', 'Adult Large'), ('AXL', 'Adult XL'), ('2X', 'Adult 2X'), ('3X', 'Adult 3X'), ('4X', 'Adult 4X')], blank=True),
        ),
        migrations.RunPython(migrate_sizes),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available_sizes_temp',
            new_name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size_code',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='size_temp',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('XS', 'Youth XS'), ('YS', 'Youth Small'), ('YM', 'Youth Medium'), ('YL', 'Youth Large'), ('YXL', 'Youth XL'), ('AS', 'Adult Small'), ('AM', 'Adult Medium'), ('AL', 'Adult Large'), ('AXL', 'Adult XL'), ('2X', 'Adult 2X'), ('3X', 'Adult 3X'), ('4X', 'Adult 4X')]),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
