# Generated by Django 5.2.6 on 2025-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_product_back_name_product_has_back_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='back_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='back_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
