# Generated by Django 5.2.6 on 2025-10-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_organization_productcolor_alter_orderitem_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
