# Generated by Django 5.2.6 on 2025-12-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_venmo',
        ),
    ]
