# Generated by Django 5.2.6 on 2025-12-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_customer_venmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_venmo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Venmo'),
        ),
    ]
