# Generated by Django 5.2.6 on 2025-12-11 03:27

from django.db import migrations, models
import uuid


def populate_order_ids(apps, schema_editor):
    """Populate order_id for all existing orders"""
    Order = apps.get_model('order', 'Order')
    for order in Order.objects.all():
        if not order.order_id:
            order.order_id = str(uuid.uuid4())
            order.save(update_fields=['order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_archived'),
    ]

    operations = [
        # Step 1: Add order_id field WITHOUT unique constraint
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Step 2: Add pending_items field
        migrations.AddField(
            model_name='order',
            name='pending_items',
            field=models.JSONField(blank=True, null=True),
        ),
        # Step 3: Populate order_id for existing records
        migrations.RunPython(populate_order_ids, reverse_code=migrations.RunPython.noop),
        # Step 4: Now add the unique constraint
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]