# Generated by Django 5.2.6 on 2025-12-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pending_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
