# Generated by Django 5.2.6 on 2025-10-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_orderitem_category_id_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
    ]
