# Generated by Django 5.2.6 on 2025-10-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_cost',
        ),
    ]
