# Generated by Django 5.2.6 on 2025-10-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_orderitem_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
